/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.smq.example

import pl.smq.lib.Library

class App {
    val library: Library = Library()
    val greeting: String
        get() {
            return "Hello World! ${library.someLibraryMethod()}"
        }
}

fun main() {
    println(App().greeting)
}
