name: Test, build and scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  server:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cppcheck
      run: sudo apt-get update & sudo apt-get install cppcheck
      
    - name: Install newer Clang
      run: |
       wget https://apt.llvm.org/llvm.sh
       chmod +x ./llvm.sh
       sudo ./llvm.sh 16


    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/server/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-16 -DCMAKE_CXX_COMPILER=clang++-16 

    - name: Build
      run: cmake --build ${{github.workspace}}/server/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/server/build
      run: ctest -C Debug

    - name: Run cppcheck
      run: cppcheck -x c++ ${{github.workspace}}/server/src/**/*

  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build
          build-root-directory: ./client

  code-scanning:
    runs-on: ubuntu-latest
    name: "Code Scanning"
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'c-cpp', 'java-kotlin' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
