name: Test, build and scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/server/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/server/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/server/build
      run: ctest -C ${{env.BUILD_TYPE}}
