name: Test, build and scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  server:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/server/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/server/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/server/build
      run: ctest -C Debug

  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build
          build-root-directory: ./client
      - name: ktlint report
        if: ${{ failure() }}
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: ktlintReport
          build-root-directory: ./client
      - name: ktlint report upload
        if: ${{ failure() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: client/report.sarif
          wait-for-processing: true
          category: ktlint
          checkout_path: "/work/smq/smq/"
